name: win32_suspend_process
description: >-
  Suspend and resume processes on the Windows platform from native dart code.
version: 1.0.0-beta.2
homepage: https://github.com/Merrit/win32_suspend_process
repository: https://github.com/Merrit/win32_suspend_process
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  win32: ^2.0.4
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
