name: win32_suspend_process
description: >-
  Suspend and resume processes on the Windows platform from native dart code.
version: 1.0.0
homepage: https://github.com/Merrit/win32_suspend_process
repository: https://github.com/Merrit/win32_suspend_process

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  win32: ^5.0.5

dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.8
