name: win32_suspend_process
description: >-
  Suspend and resume processes on the Windows platform from native dart code.
version: 0.1.3
homepage: https://github.com/Merrit/win32_suspend_process
repository: https://github.com/Merrit/win32_suspend_process
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  win32: ^1.7.4+1
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
